parameters:
    orocrm_abandonedcart_list.form.type.abandonedcart_list.class: OroCRM\Bundle\AbandonedCartBundle\Form\Type\AbandonedCartListType
    orocrm_abandonedcart_list.form.type.marketing_type_hidden.class: OroCRM\Bundle\AbandonedCartBundle\Form\Type\AbandonedCartHiddenMarketingListTypeType
    orocrm_abandonedcart_list.form.handler.abandonedcart_list.class: OroCRM\Bundle\AbandonedCartBundle\Form\Handler\AbandonedCartListHandler

    orocrm_mailchimp.form.type.abandonedcart_list_conversion.class: OroCRM\Bundle\AbandonedCartBundle\Form\Type\AbandonedCartConversionType
    orocrm_mailchimp.form.handler.conversion_form.class: OroCRM\Bundle\AbandonedCartBundle\Form\Handler\ConversionFormHandler

services:
    # AbandonedCartList
    orocrm_abandonedcart_list.form.type.abandonedcart_list:
        class: %orocrm_abandonedcart_list.form.type.abandonedcart_list.class%
        tags:
            - { name: form.type, alias: orocrm_abandonedcart_list }

    orocrm_abandonedcart_list.form.abandonedcart_list:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_abandonedcart_list_form"
            - "orocrm_abandonedcart_list"

    orocrm_abandonedcart_list.form.type.marketing_type_hidden:
        class: %orocrm_abandonedcart_list.form.type.marketing_type_hidden.class%
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: orocrm_abandonedcart_list_marketing_list_type_hidden }

    orocrm_abandonedcart_list.form.handler.abandoned_cart_list:
        class: %orocrm_abandonedcart_list.form.handler.abandonedcart_list.class%
        scope: request
        arguments:
            - @orocrm_abandonedcart_list.form.abandonedcart_list
            - @request
            - @doctrine
            - @validator
            - @translator
            - @orocrm_abandonedcart.marketing_list.source
            - @orocrm_abandonedcart_list.campaign_factory
            - @orocrm_abandonedcart_list.campaign_abandonedcart_relation_factory

    orocrm_mailchimp.form.type.abandonedcart_list_conversion:
        class: %orocrm_mailchimp.form.type.abandonedcart_list_conversion.class%
        arguments:
            - @orocrm_abandonedcart.conversion_manager
        tags:
            - { name: form.type, alias: "orocrm_mailchimp_abandonedcart_list_conversion" }

    orocrm_mailchimp.form.abandonedcart_list_conversion:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["orocrm_mailchimp_abandonedcart_list_conversion", "orocrm_mailchimp_abandonedcart_list_conversion", null]

    orocrm_mailchimp.form.handler.conversion_form:
        class: %orocrm_mailchimp.form.handler.conversion_form.class%
        scope: request
        arguments: ["@orocrm_mailchimp.form.abandonedcart_list_conversion", "@request", "@doctrine.orm.entity_manager"]

