parameters:
    orocrm_abandonedcart_list.form.type.abandonedcart_list.class: OroCRM\Bundle\AbandonedCartBundle\Form\Type\AbandonedCartListType
    orocrm_abandonedcart_list.form.handler.abandoned_cart_list.class: OroCRM\Bundle\AbandonedCartBundle\Form\Handler\AbandonedCartListHandler

services:
    # AbandonedCartList
    orocrm_abandonedcart_list.form.type.abandonedcart_list:
        class: %orocrm_abandonedcart_list.form.type.abandonedcart_list.class%
        tags:
            - { name: form.type, alias: orocrm_abandonedcart_list }

    orocrm_abandonedcart_list.form.abandonedcart_list:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_abandonedcart_list_form"
            - "orocrm_abandonedcart_list"

    orocrm_abandonedcart_list.form.handler.abandoned_cart_list:
        class: %orocrm_abandonedcart_list.form.handler.abandoned_cart_list.class%
            scope: request
            arguments:
                - @orocrm_abandonedcart_list.form.abandonedcart_list
                - @request
                - @doctrine.orm.entity_manager
                - @orocrm_abandonedcart.abandoned_cart_list.manager
                - @orocrm_abandonedcart.segment_definition_helper
