parameters:
    orocrm_abandonedcart_list.form.type.abandonedcart_list.class: OroCRM\Bundle\AbandonedCartBundle\Form\Type\AbandonedCartListType

    orocrm_abandonedcart.form.handler.abandonedcart_campaign.class: OroCRM\Bundle\AbandonedCartBundle\Form\Handler\AbandonedCartCampaignHandler
    orocrm_abandonedcart.campaign_factory.class: OroCRM\Bundle\AbandonedCartBundle\Model\AbandonedCartList\CampaignFactory
    orocrm_abandonedcart.abandonedcart_campaign_factory.class: OroCRM\Bundle\AbandonedCartBundle\Model\AbandonedCartList\AbandonedCartCampaignFactory

services:
    # AbandonedCartList
    orocrm_abandonedcart_list.form.type.abandonedcart_list:
        class: %orocrm_abandonedcart_list.form.type.abandonedcart_list.class%
        tags:
            - { name: form.type, alias: orocrm_abandonedcart_list }

    orocrm_abandonedcart_list.form.abandonedcart_list:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_abandonedcart_list_form"
            - "orocrm_abandonedcart_list"

    orocrm_abandonedcart.campaign_factory:
        class: %orocrm_abandonedcart.campaign_factory.class%

    orocrm_abandonedcart.abandonedcart_campaign_factory:
        class: %orocrm_abandonedcart.abandonedcart_campaign_factory.class%
        arguments:
            - @orocrm_abandonedcart.campaign_factory

    orocrm_abandonedcart.form.handler.abandonedcart_campaign:
        class: %orocrm_abandonedcart.form.handler.abandonedcart_campaign.class%
        scope: request
        arguments:
            - @orocrm_abandonedcart_list.form.abandonedcart_list
            - @request
            - @doctrine
            - @validator
            - @translator
            - @orocrm_abandonedcart.abandonedcart_campaign_factory
            - @orocrm_abandonedcart.provider
