oro_menu_config:
    items:
        abandoned_cart_list:
            label: 'orocrm.abandonedcart.abandonedcartlist.entity_plural_label'
            route: 'orocrm_abandoned_cart_list'
    tree:
        application_menu:
            children:
                marketing_tab:
                    children:
                        abandoned_cart_list: ~

oro_titles:
    orocrm_abandoned_cart_list:  ~
    orocrm_abandoned_cart_list_view: '%%entityName%%'



