oro_menu_config:
    items:
        abandoned_cart_list:
            label: 'orocrm.abandonedcart.abandonedcartlist.entity_plural_label'
            route: 'orocrm_abandoned_cart_list'
            extras:
                routes: ['orocrm_abandoned_cart_list_*']
                position: 10
    tree:
        application_menu:
            children:
                marketing_tab:
                    children:
                        abandoned_cart_list: ~

oro_titles:
    orocrm_abandoned_cart_list:  ~
    orocrm_abandoned_cart_list_view: '%%entityName%%'
    orocrm_abandoned_cart_list_update: '%%entityName%% - Edit'
    orocrm_abandoned_cart_list_create: oro.ui.create_entity


