placeholders:
    mailchimp_workflow_button:
        items:
            orocrm_mailchimp_abandonedcart_enable_conversion_button: ~

items:
    orocrm_mailchimp_abandonedcart_enable_conversion_button:
        action: OroCRMAbandonedCartBundle:AbandonedCartConversion:conversionButton
