parameters:
    orocrm_abandonedcart.entity.abandonedcart_campaign.class: OroCRM\Bundle\AbandonedCartBundle\Entity\AbandonedCartCampaign
    orocrm_abandonedcart.entity.marketing_list_type.class: OroCRM\Bundle\MarketingListBundle\Entity\MarketingListType

    orocrm_abandonedcart.abandoned_cart_list.campaign_manager.class: OroCRM\Bundle\AbandonedCartBundle\Model\AbandonedCartList\CampaignAbandonedCartRelationManager
    orocrm_abandonedcart.predefined_marketing_list_factory.class: OroCRM\Bundle\AbandonedCartBundle\Model\AbandonedCartList\PredefinedMarketingListFactory
    orocrm_abandonedcart.campaign_factory.class: OroCRM\Bundle\AbandonedCartBundle\Model\AbandonedCartList\CampaignFactory
    orocrm_abandonedcart.extended_merge_var.provider.cart_items.class: OroCRM\Bundle\AbandonedCartBundle\Model\ExtendedMergeVar\CartItemsMergeVarProvider
    orocrm_abandonedcart.importexport.strategy.member_cartitems_merge_var.listener.class: OroCRM\Bundle\AbandonedCartBundle\ImportExport\Strategy\CartItemsMergeVarStrategyListener
    orocrm_abandonedcart.provider.class: OroCRM\Bundle\AbandonedCartBundle\Model\AbandonedCartCampaignProvider
    orocrm_abandonedcart.marketing_list.datagrid.listener.class: OroCRM\Bundle\AbandonedCartBundle\Datagrid\MarketingListListener
    orocrm_abandonedcart.datagrid.listener.class: OroCRM\Bundle\AbandonedCartBundle\Datagrid\AbandonedCartCampaignListener
    orocrm_abandonedcart.event_listener.datagrid.class: OroCRM\Bundle\AbandonedCartBundle\EventListener\Datagrid\AbandonedCartListener

    orocrm_abandonedcart.marketing_list.datagrid.name: orocrm-marketing-list-grid
    orocrm_abandonedcart.datagrid.name: orocrm-abandonedcart-list-grid
    orocrm_abandonedcart.extended_merge_var.cart_item.template: OroCRMAbandonedCartBundle:ExtendedMergeVar:cartItemMergeVar.txt.twig

    orocrm_abandonedcart.event_listener.navigation.class: OroCRM\Bundle\AbandonedCartBundle\EventListener\NavigationListener
    orocrm_abandonedcart.listener.datagrid.abandonedcart_list.class: OroCRM\Bundle\AbandonedCartBundle\EventListener\Datagrid\AbandonedCartGridListener

services:
    orocrm_abandonedcart.abandoned_cart_list.campaign_manager:
        class: %orocrm_abandonedcart.abandoned_cart_list.campaign_manager.class%
        arguments:
            - @doctrine
            - %orocrm_abandonedcart.entity.abandonedcart_campaign.class%

    orocrm_abandonedcart.provider:
        class: %orocrm_abandonedcart.provider.class%
        arguments:
            - @doctrine

    orocrm_abandonedcart.marketing_list.datagrid.listener:
        class: %orocrm_abandonedcart.marketing_list.datagrid.listener.class%
        arguments:
            - %orocrm_abandonedcart.marketing_list.datagrid.name%
            - %orocrm_abandonedcart.entity.abandonedcart_campaign.class%
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after, method: onBuildAfter }

    orocrm_abandonedcart.datagrid.listener:
        class: %orocrm_abandonedcart.datagrid.listener.class%
        arguments:
            - %orocrm_abandonedcart.datagrid.name%
            - %orocrm_abandonedcart.entity.abandonedcart_campaign.class%
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after, method: onBuildAfter }

    orocrm_abandonedcart.predefined_marketing_list_factory:
        class: %orocrm_abandonedcart.predefined_marketing_list_factory.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %orocrm_magento.cart.entity.class%
            - %orocrm_abandonedcart.entity.marketing_list_type.class%

    orocrm_abandonedcart.campaign_factory:
        class: %orocrm_abandonedcart.campaign_factory.class%

    orocrm_abandonedcart.extended_merge_var.provider.cart_items:
        class: %orocrm_abandonedcart.extended_merge_var.provider.cart_items.class%
        arguments:
            - @orocrm_abandonedcart.provider
            - @translator
        tags:
            - { name: orocrm_mailchimp.extended_merge_vars.provider }

    orocrm_abandonedcart.importexport.strategy.member_cartitems_merge_var.listener:
        class: %orocrm_abandonedcart.importexport.strategy.member_cartitems_merge_var.listener.class%
        arguments:
            - @oro_entity.doctrine_helper
            - @twig
            - %orocrm_abandonedcart.extended_merge_var.cart_item.template%
        tags:
            - { name: kernel.event_listener, event: oro_importexport.strategy.process_after, method: onProcessAfter }

    orocrm_abandonedcart.event_listener.datagrid:
        class: %orocrm_abandonedcart.event_listener.datagrid.class%
        arguments:
            - @orocrm_marketing_list.model.helper
            - @orocrm_abandonedcart.provider
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.orocrm-marketing-list-items-base-unsubscribe-mixin, method: onBuildBefore }

    # event listeners
    orocrm_channel.event_listener.navigation:
        class: %orocrm_abandonedcart.event_listener.navigation.class%
        arguments:
            - @doctrine
        tags:
            - { name: kernel.event_listener, event: oro_menu.configure.application_menu, method: onNavigationConfigure }

    orocrm_abandonedcart.listener.datagrid.abandonedcart_list:
        class: %orocrm_abandonedcart.listener.datagrid.abandonedcart_list.class%
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.orocrm-marketing-list-grid, method: onBuildBefore }
