parameters:
    orocrm_abandonedcart_list.entity.class:  OroCRM\Bundle\AbandonedCartBundle\Entity\AbandonedCartList
    orocrm_abandonedcart_list.twig.extension.contact_information_fields.class: OroCRM\Bundle\AbandonedCartBundle\Twig\ContactInformationFieldsExtension
    orocrm_abandonedcart.segment_definition_helper.class: OroCRM\Bundle\AbandonedCartBundle\Model\SegmentDefinitionHelper
        orocrm_abandonedcart.abandoned_cart_list.manager.class: OroCRM\Bundle\AbandonedCartBundle\Model\AbandonedCartListManager
        orocrm_abandonedcart.dynamic_type_segment.builder.class: OroCRM\Bundle\AbandonedCartBundle\Model\AbandonedCartList\DynamicTypeSegmentBuilder

services:
    orocrm_abandonedcart_list.twig.extension.contact_information_fields:
        class: %orocrm_abandonedcart_list.twig.extension.contact_information_fields.class%
        arguments:
            - @orocrm_marketing_list.contact_information_field_helper
        tags:
            - { name: twig.extension }

    orocrm_abandonedcart.segment_definition_helper:
        class: %orocrm_abandonedcart.segment_definition_helper.class%

    orocrm_abandonedcart.dynamic_type_segment.builder:
        class: %orocrm_abandonedcart.dynamic_type_segment.builder.class%
            arguments:
                - @doctrine.orm.entity_manager

    orocrm_abandonedcart.abandoned_cart_list.manager:
        class: %orocrm_abandonedcart.abandoned_cart_list.manager.class%
            arguments:
                - @orocrm_abandonedcart.dynamic_type_segment.builder
                - @translator
