parameters:
    orocrm_abandonedcart_list.twig.extension.contact_information_fields.class: OroCRM\Bundle\AbandonedCartBundle\Twig\ContactInformationFieldsExtension
    orocrm_abandonedcart_list.twig.extension.campaign.class: OroCRM\Bundle\AbandonedCartBundle\Twig\CampaignExtension
    orocrm_abandonedcart.abandoned_cart_list.campaign_manager.class: OroCRM\Bundle\AbandonedCartBundle\Model\AbandonedCartList\CampaignAbandonedCartRelationManager
    orocrm_abandonedcart.marketing_list.source.class: OroCRM\Bundle\AbandonedCartBundle\Model\MarketingList\AbandonedCartSource
    orocrm_abandonedcart_list.predefined_marketing_list_factory.class: OroCRM\Bundle\AbandonedCartBundle\Model\AbandonedCartList\PredefinedMarketingListFactory
    orocrm_abandonedcart_list.campaign_factory.class: OroCRM\Bundle\AbandonedCartBundle\Model\AbandonedCartList\CampaignFactory

services:
    orocrm_abandonedcart_list.twig.extension.contact_information_fields:
        class: %orocrm_abandonedcart_list.twig.extension.contact_information_fields.class%
        arguments:
            - @orocrm_marketing_list.contact_information_field_helper
        tags:
            - { name: twig.extension }

    orocrm_abandonedcart_list.twig.extension.campaign:
        class: %orocrm_abandonedcart_list.twig.extension.campaign.class%
        arguments:
            - @orocrm_abandonedcart.abandoned_cart_list.campaign_manager
        tags:
            - { name: twig.extension }

    orocrm_abandonedcart.abandoned_cart_list.campaign_manager:
        class: %orocrm_abandonedcart.abandoned_cart_list.campaign_manager.class%
        arguments:
            - @doctrine.orm.entity_manager

    orocrm_abandonedcart.marketing_list.source:
        class: %orocrm_abandonedcart.marketing_list.source.class%

    orocrm_abandonedcart.datagrid.listener:
        class: %orocrm_marketing_list.datagrid.listener.class%
        arguments:
            - 'orocrm-abandonedcart-list-grid'
            - @orocrm_abandonedcart.marketing_list.source
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after, method: onBuildAfter }

    orocrm_abandonedcart_list.predefined_marketing_list_factory:
        class: %orocrm_abandonedcart_list.predefined_marketing_list_factory.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @orocrm_abandonedcart.marketing_list.source

    orocrm_abandonedcart_list.campaign_factory:
        class: %orocrm_abandonedcart_list.campaign_factory.class%
