OroCRM\Bundle\AbandonedCartBundle\Entity\AbandonedCartList:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ name ]
    properties:
        name:
            - NotBlank:     ~
            - Length:
                max: 255
        organization:
            - NotBlank: ~
